import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
   return (
      <div>
         <Head>
            <title>C.Harris Portfolio</title>
            <meta
               name='description'
               content='Generated by create next app'
            />
         </Head>
         <main>
            <section>
               <div>
                  <h2>Courtney Harris</h2>
                  <h3>Full-stack engineer and photographer</h3>
                  {/* <p>
                     First let me say welcome to my page!
                     <br />
                     So about me...I am a banker turned software
                     engineer. I spent 10+ yrs in banking, playing
                     around with coding for a while unitl I finally
                     decided to jump in head first. Now, I am building
                     sites, learning Web3 and on the job hunt!
                  </p> */}
               </div>
            </section>
         </main>
      </div>
   );
}
